name: puzzle_game
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.0-208.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.3.3
  transparent_image: ^1.0.0
  get: 4.6.1
  animated_widgets: ^1.1.0
  flutter_slidable: ^1.2.0
  slide_to_act: ^2.0.1
 # spannable_grid: ^0.3.0
  lottie: ^1.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true


  assets:
    - assets/

